### ISSUE TITLE
Mark workflow run as neutral or success when skipping

### ISSUE THREAD

**Issue by riker09** [agilepathway/label-checker#227]
I want to run a workflow on `pull_request` trigger when a certain label is assigned to the PR. I use this action to check and the workflow is cancelled when the label is not present, so this action right here works as intended.

However, the workflow run is marked as `failed` in my GitHub UI, when in reality it should not have run at all. Is there a way to achive this behaviour? Judging from the discussion at https://github.com/actions/toolkit/issues/399 this is something that only the GitHub team could solve.

I've read in a blog post from the official GitHub Actions Blog that GitHub will skip any `push` or `pull_request` events that have `[skip ci]` in their commit messages. But what I really want is the other way around.

**Comment by riker09** [comment]
To answer my own question:

```yaml
on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-20.04
    continue-on-error: true
    outputs:
      sha7: ${{ steps.prepare.outputs.sha7 }}
    steps:
    - id: check-label
      uses: agilepathway/label-checker@v1.0.90
      continue-on-error: true
      with:
        one_of: cicd
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - if: steps.check-label.outcome == 'success'
      run: |
        echo "::set-output name=sha7::${GITHUB_SHA:0:7}"

  build:
    if: needs.prepare.outputs.sha7
    runs-on: ubuntu-20.04
    needs: prepare

    steps:
      - uses: actions/checkout@v2

    # ...
```

this marks the PR check as `success`, though. But this is better than `failure` in my opinion. Gotta love them little green checkmarks. 😃
