### ISSUE TITLE
Tests fail when only `all_of` is specified

### ISSUE THREAD

**Issue by vincetiu8** [agilepathway/label-checker#248]
`workflow.yml`:
```
jobs:
  check-labels:
    name: Check Labels
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@v1.0.9
        with:
          all_of: dependencies
          repo_token: ${{ secrets.GITHUB_TOKEN }}
```

expectation:
- tests should pass, only checking tha `all_of` condition.

output:
```
Run agilepathway/label-checker@v1.0.9
/usr/bin/docker run --name c9e036bdf4c5186c704eeba3d0619efcea84d7_f9d086 --label c9e036 --workdir /github/workspace --rm -e INPUT_ALL_OF -e INPUT_REPO_TOKEN -e INPUT_ONE_OF -e INPUT_NONE_OF -e INPUT_ANY_OF -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/palm/palm":"/github/workspace" c9e036:bdf4c5186c704eeba3d0619efcea84d7
Checking GitHub labels ...
Error: Label check failed: required 1 of , but found 0.
Label check failed: required any of , but found 0.
Label check successful: required none of , and found 0.
Label check successful: required all of dependencies, and found 1: dependencies
```
