### ISSUE TITLE
Integration with GitHub merge-queue

### ISSUE THREAD

**Issue by yanns** [agilepathway/label-checker#366]
When using [GitHub merge-queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue), GitHub creates new branch for merging pull requests.

This brings two issues.

First, the label checker is running only on pull requests:
The documentation specifies the trigger as follow:
```
on:
  pull_request:
```

This can be fixed by adding this [trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group):
```
  merge_group:
    types: [checks_requested]
```

Second, even if we run the label checker on those branches to be merged, we have an issue as they are no pull requests for them, and no labels. The check fails with the error message:
```
Checking GitHub labels ...
2023/03/02 10:34:20 Error that we cannot handle, Could not resolve to a PullRequest with the number of 0.
```

What can we do?
Maybe we can detect if the action is run for a branch for the merge-queue, and always succeed in that case?

**Comment by yanns** [comment]
Related to https://github.com/orgs/community/discussions/13690

**Comment by yanns** [comment]
👍 
I'll add some info to this issue if I find a solution.

**Comment by yanns** [comment]
OK I found a way to make it work. I hope this can help others.

```
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  merge_group:
    types: [checks_requested]

jobs:
  check_labels:
    if: github.event_name == 'pull_request'
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
```

Explanations:
- the action run on merge branches thanks to the `on merge_group`
- the action does not do anything on merge branches thanks to the `if: github.event_name == 'pull_request'`. GitHub accepts this and the PR can be merged.
