### ISSUE TITLE
Action does not seem to work with pull_request_review event

### ISSUE THREAD

**Issue by piotrekkr** [agilepathway/label-checker#385]
We use workflow like this:
```
name: Trigger Full Check Suite

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: "read"
  contents: "read"

jobs:
  trigger-full-check-suite:
    name: Trigger full check suite
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Check if label exist
        id: check
        uses: docker://agilepathway/pull-request-label-checker:v1.4.26@sha256:9447314abafef2d0245c594352538e16a410a9294a4c03b6218d94d2c474e699
        with:
          all_of: run-full-check-suite
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true
```
but what we get is error

```
Checking GitHub labels ...
2023/08/18 14:41:38 Error that we cannot handle, Could not resolve to a PullRequest with the number of 0.
```

![image](https://github.com/agilepathway/label-checker/assets/503782/fbf68ea2-e1a4-4f94-ae0b-30fab05e2641)

It is a pity that there is no way to manually specify PR number. It would fix our problem.

**Comment by johnboyes** [comment]
Hi @piotrekkr, thanks for raising this.  I'll have a look into it to see if I can add this feature.  May be a few weeks, I'll keep you posted.

**Comment by piotrekkr** [comment]
I think I will manage prepare a PR even without knowing go too much. Should be simple fix.

**Comment by johnboyes** [comment]
Thanks for the contribution, @piotrekkr!  I merged [your PR](https://github.com/agilepathway/label-checker/pull/386), and it has been released in [v.1.5.0](https://github.com/agilepathway/label-checker/releases/tag/v1.5.0) 👍🏻

**Comment by piotrekkr** [comment]
Thanks :pray:

**Comment by johnboyes** [comment]
Hi @piotrekkr, I _think_ that this change may have introduced a defect in some scenarios (see #392).  So I have reverted this  change for now.  You can continue to use the [v1.5.0](https://github.com/agilepathway/label-checker/releases/tag/v1.5.0) release if it's working ok for you.  I'm about to go on holiday for a week, and when I return I'll look properly into a fix which allows me to re-release this feature for you in another PR. Hope that's ok and makes sense 🙏🏻

**Comment by piotrekkr** [comment]
@garaujodev Can you tell what kind of event type it is exactly that is generating this error? It works for me for `pull_request_review` and also `pull_request`.

![image](https://github.com/agilepathway/label-checker/assets/503782/fbeaea0a-88e2-45aa-a98c-e831a27a58c5)

My workflow looks like this:
```yaml
name: Check labels

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-labels:
    name: Check PR labels
    runs-on: ubuntu-22.04
    steps:
      - name: Golden master label validation
        uses: docker://agilepathway/pull-request-label-checker:v1.5.0
        with:
          one_of: golden-master-validated
          none_of: do-not-merge
          repo_token: ${{ secrets.GITHUB_TOKEN }}
```
