### ISSUE TITLE
Workflow failure: Could not resolve to a PullRequest with the number of 0

### ISSUE THREAD

**Issue by garaujodev** [agilepathway/label-checker#392]
I'm getting consecutive failures in the workflow. This is my output:

```
Checking GitHub labels ...
2023/09/06 12:23:33 Error that we cannot handle, Could not resolve to a PullRequest with the number of 0.
```

## My workflow file

```
name: Label checker
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: fix,feature,build,documentation,refactor,chore,style,test,performance,revert
          none_of: blocked
          repo_token: ${{ secrets.GITHUB_TOKEN }}
```

Any ideas?

**Comment by johnboyes** [comment]
Hi @garaujodev, thanks for raising this.  I suspect this was inadvertently caused by [v1.5.0](https://github.com/agilepathway/label-checker/releases/tag/v1.5.0) which was released last week.  I'm about to go on holiday for a week, so as I don't have time to find the proper fix before I go I'll revert that change in a new release, working on that right now.

**Comment by johnboyes** [comment]
Done, I have created a new release [v1.5.4](https://github.com/agilepathway/label-checker/releases/tag/v1.5.4) which reverts the suspect [v1.5.0](https://github.com/agilepathway/label-checker/releases/tag/v1.5.0) change.  @garaujodev please confirm that this has fixed things for you, thanks.

**Comment by piotrekkr** [comment]
@garaujodev Can you tell what kind of event type it is exactly that is generating this error? It works for me for `pull_request_review` and also `pull_request`.

![image](https://github.com/agilepathway/label-checker/assets/503782/fbeaea0a-88e2-45aa-a98c-e831a27a58c5)

My workflow looks like this:
```yaml
name: Check labels

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-labels:
    name: Check PR labels
    runs-on: ubuntu-22.04
    steps:
      - name: Golden master label validation
        uses: docker://agilepathway/pull-request-label-checker:v1.5.0
        with:
          one_of: golden-master-validated
          none_of: do-not-merge
          repo_token: ${{ secrets.GITHUB_TOKEN }}
```

//EDIT 

Also checked with `latest` version and it works too.
