### ISSUE TITLE
Allow to use label checker with milestoned/demilestoned trigger

### ISSUE THREAD

**Issue by Czaki** [agilepathway/label-checker#412]
In our project we would like to have one job to check if labels and milestone are set properly. Unfortunately the milestoned/demilestoned trigger is emitted as `issues`, not pull request name. 

But if event is touching pull request then `github.event.issue.pull_request` is not `null` and number could be received from `github.event.issue` object 

https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=milestoned#issues

It will be really nice if you could add this functionality to this project (or I may try to do PR if you want).

**Comment by johnboyes** [comment]
Hi @Czaki, thanks for suggesting this.  Can you provide an end-to-end example (not the technical "how" but rather an example of the end-to-end workflow you're looking for), to help me understand and evaluate whether it's something we could/should add to the label checker?  Thanks very much 🙏🏻

**Comment by Czaki** [comment]
I have spent more time investigating the problem. The issue trigger is not helpful at all, as it is not visible in pull request check status. So my idea is useless. But I found in the documentation of the payload that the milestoned/demilestoned triggers are available:

https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=milestoned#pull_request

And I have checked that it works. Even if documentation do not mention it in any place.

Our workflow (state from open PR) looks now:

```yaml
name: Label and milestone checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - milestoned
      - demilestoned
  merge_group: # to be prepared on merge queue
    types: [checks_requested]

jobs:
  check_labels_and_milestone:
    if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ready to merge'))
    name: Check labels and milestone
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: bugfix,feature,documentation,performance,enhancement,maintenance
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check milestone
        if: github.event.pull_request.milestone == null
        run: |
          echo "Please add a milestone to this PR"
          exit 1
```

Sorry for the noise. I have opened PR to github docs https://github.com/github/docs/pull/29837
